function dA = adjoint_model(t,Y,A,U,p)

PT = Y(1);
PH = Y(2);
PR = Y(3);
PN = Y(4);
PD = Y(5);
PE = Y(6);
PS = Y(7);

u1 = U(1);
u2 = U(2);
u3 = U(3);

A1 = A(1);
A2 = A(2);
A3 = A(3);
A4 = A(4);
A5 = A(5);
A6 = A(6);
A7 = A(7);

%% A1'

dA1 = -( ...
    p.c1 ...
    + A1*( ...
    p.r1*(1-2*PT/p.k1) ...
    -p.alpha1*PH ...
    -p.alpha2*PN ...
    -p.alpha3*PD ...
    +p.lambda_ST*PS/(p.KS+PS)) ...
    + A2*(-p.sigma2*PH) ...
    + A3*(p.rho*p.eta*PR/(PT+p.eta)^2) ...
    + A4*(-p.delta1*PN) );

%% A2'

dA2 = -( ...
    A1*(-p.alpha1*PT) ...
    + A2*( ...
    p.beta*PR/(1+p.kh*PS) ...
    -p.sigma1 ...
    -p.sigma2*PT ...
    -p.sigma3*PD) ...
    + A3*(-p.rho1*PR) );

%% A3'

dA3 = -( ...
    A2*(p.beta*PH/(1+p.kh*PS)) ...
    + A3*( ...
    p.r2*(1-2*PR/p.k2) ...
    -p.rho1*PH ...
    -p.rho2 ...
    +p.rho*PT/(PT+p.eta) ...
    -p.rho3*PD ...
    -p.lambda3*PE/...
    ((p.g+PE)*(1+p.xi*PD))) );

%% A4'

dA4 = -( ...
    A1*( ...
    -p.alpha2*PT ...
    +p.lambda1*PE/(1+p.xi*PD)) ...
    + A4*( ...
    p.r3*(1-2*PN/p.k3) ...
    -p.delta1*PT ...
    -p.delta2 ...
    -p.delta3*PD ...
    -p.lambda1*PE/(1+p.xi*PD) ...
    -p.lambda_SN*PS/(p.KS+PS)) );

%% A5'

dA5 = -( ...
    A1*( ...
    -p.alpha3*PT ...
    -p.lambda1*p.xi*PN*PE/(1+p.xi*PD)^2) ...
    + A2*(-p.sigma3*PH) ...
    + A3*( ...
    -p.rho3*PR ...
    +p.lambda3*p.xi*PR*PE/...
    ((p.g+PE)*(1+p.xi*PD)^2)) ...
    + A4*( ...
    -p.delta3*PN ...
    +p.lambda1*p.xi*PN*PE/(1+p.xi*PD)^2) ...
    -p.gamma*A5 ...
    -p.xi*PE*A6 );

%% A6'

dA6 = -( ...
    A1*(p.lambda1*PN/(1+p.xi*PD)) ...
    -A3*( ...
    p.lambda3*p.g*PR/...
    ((p.g+PE)^2*(1+p.xi*PD))) ...
    + A4*(-p.lambda1*PN/(1+p.xi*PD)) ...
    - A6*(p.mu4+p.xi*PD+u2+u3) );

%% A7'

dA7 = -( ...
    A1*(p.lambda_ST*PT*p.KS/(p.KS+PS)^2) ...
    + A2*(-p.beta*p.kh*PR*PH/(1+p.kh*PS)^2) ...
    + A4*(-p.lambda_SN*PN*p.KS/(p.KS+PS)^2) ...
    - A7*(p.dS+u3) );

dA = [dA1;
      dA2;
      dA3;
      dA4;
      dA5;
      dA6;
      dA7];

end