function dY = controlled_model(t,Y,U,p)

% State variables
PT = Y(1);
PH = Y(2);
PR = Y(3);
PN = Y(4);
PD = Y(5);
PE = Y(6);
PS = Y(7);

% Controls
u1 = U(1);
u2 = U(2);
u3 = U(3);

%% State equations

dPT = ...
    p.r1*PT*(1-PT/p.k1) ...
    -p.alpha1*PT*PH ...
    -p.alpha2*PT*PN ...
    -p.alpha3*PT*PD ...
    +p.lambda_ST*PS*PT/(p.KS+PS) ...
    +p.lambda1*PN*PE/(1+p.xi*PD);

dPH = ...
    p.beta*PR*PH/(1+p.kh*PS) ...
    -p.sigma1*PH ...
    -p.sigma2*PT*PH ...
    -p.sigma3*PH*PD;

dPR = ...
    p.r2*PR*(1-PR/p.k2) ...
    -p.rho1*PR*PH ...
    -p.rho2*PR ...
    +p.rho*PT*PR/(PT+p.eta) ...
    -p.rho3*PR*PD ...
    -p.lambda3*PR*PE/...
    ((p.g+PE)*(1+p.xi*PD));

dPN = ...
    p.r3*PN*(1-PN/p.k3) ...
    -p.delta1*PT*PN ...
    -p.delta2*PN ...
    -p.delta3*PN*PD ...
    -p.lambda1*PN*PE/(1+p.xi*PD) ...
    -p.lambda_SN*PS*PN/(p.KS+PS);

dPD = u1 - p.gamma*PD;

dPE = ...
    p.epsilon*(1-u2) ...
    -(p.mu4+p.xi*PD+u2+u3)*PE;

dPS = ...
    p.kS*(1-u3) ...
    -(p.dS+u3)*PS;

dY = [dPT;
      dPH;
      dPR;
      dPN;
      dPD;
      dPE;
      dPS];

end